language: node_js
node_js:
- '4.2'
deploy:
  local_dir: build
  provider: s3
  skip_cleanup: true
  bucket: pebblecode-wfh
script:
- npm run build
env:
  global:
  - secure: rDC7QPUns3Yxy2QfNdExIiRL38E+K3+vKwKLRLrR+1657lU7Ib1dgIMaEk72NFYxvUN7mBNtMjcHPGD7xQt+Gh6T36hNrZHSXBJEEoutLzveZwYgoa5qyBHXVKXiaUDeuHytKqByS3+CZIhFJC4hxFv4wUtWMIn0r9jXLcN/bfHcCbb8OvagOk51FS+iHpiHyl9TJH7onQs2kAdN1VYP6SriiFGt6BN7lNzgvAXp19enCZKImhMKBOiVOoK+yfDxV9soznAg1tnYyRa9r8++OwhlMU5h0jcWwVAgF+BFYG9qKPn7aMh9Rm3i/3hkQNqtRWMsvGm2IbnJhL+Gs7LLScJ9ieYr+Q73Pb1CaybC742XFqjzuRJlcPVkvU6io0kFOdJIN8fBMXZ0CDmxi3CJRedi9jkqsdrR1xGapYhNhYR85r4nRJjDNR7NEN1d4VKIgjFN+vPbdZFZo74D4qUpXV/I4+rVgdp/fyeEqwC4FuZRvWYILu4d6clKghEO0gmsfNBazzjSLQBAVGqW/9MeQqVFRp971IJk2PjktjkfISUfHVz6kSguhazL6H+WdcyJf8mkY03V0m8vr6LGdZTZABZI784kUVIzE2+6Q5QvNtWk13u3FuS1YMmQ9C85lwQOey3JYbwmCwZJbBCrUFhBL2566pLP9VmTTwTVMNxOsrc=
  - secure: FUl0IO1jwzpetqoA3g1BIgvyX9G/iFw64bfGKZPPsNHb5W4FyRelbxVIQ/XdG0FFkRZpcbx49a9YZoew6GCNHFk+Y/Y1NJXxZVr8ejGUqUB64tMFRmfpbwU6yk2i2/zmMlWzzfjW1IlNjserchHPZU1klocb3Hv6Vatx73DL0ylScxCsn9/xMTxkxUUI1vvF/aeWj5RsKPDuHLgRhq0yL8MgFn5mGjT0nyrfY9p0/yUx82dw8IIXpe3NGZAQBSlZWogC0FU31Dpoffs1u68vgsHTHcYGSjedxdBsWdMDs3pfdl698cPKpLnN9QyyN5g9627JsKL0RtBehtv04yzDHNUZ1/Y66X8TWl3pdX1GEl9zDr4+1KvC6onnaw9ol0WevOTwMBBIlxSDaQpDyfQ/bg3C+VLPAe6bWq+ANeiS3710I6oH770sgCMfF0vabtGN4HHyoCHP29hLL3vasAW9vGphHhqitrR3cHs9WTa1AzaPsSLM9BTE4K/VJecYbGdKugZsE3IPKtRr7JvEKFnuNGNvFBbhXQ/KslCkJcEoBUNuFjk/7TP+n2tZRNl2cBgk2+dOXyw4cq3qgaBWm8dSmd9W5eAGU03nMu/AWALr3TNxFHKAcXhJQ/fsQVQ6cYKXYRvtxI6lR8l5dQ3zFvyVc+1LUNU42rP2XXqh5ROqbKQ=
